packages:
  - packages/app
  - packages/sdk
  - packages/discord-bridge
  - packages/tsconfig
onlyBuiltDependencies:
  - "@swc/core"
  - "@tailwindcss/oxide"
  - cbor-extract
  - core-js
  - esbuild
  - node
# patchedDependencies:
#   "@discordeno/gateway": patches/@discordeno__gateway.patch
