[package]
name = "roomy-render"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = []

[dependencies]
minijinja = { version = "1.0", default-features = false, features = ["loader"] }
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3"
serde-wasm-bindgen = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "1.19"
ahash = { version = "=0.8.11", default-features = false, features = [
  "compile-time-rng",
] } # Exact version pin
# jsonschema = { version = "0.29.1", default-features = false }
getrandom = { version = "0.2", features = ["js"] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O", "--enable-simd"]

[profile.test]
opt-level = 1 # Enable some optimizations even for tests

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
debug = false
panic = 'abort'   # Remove panic unwinding code
strip = true      # Strip symbols (nightly only)